### ISSUE TITLE
1.17.1 crash

### ISSUE THREAD

**Issue by funcraft31** [SamB440/Tale-of-Kingdoms#133]
### Summary

tale of kingdom mod 1.17.1 fabric crashes cant even open game on crash report says 

Caused by: java.lang.IllegalArgumentException: No enum constant com.convallyria.taleofkingdoms.common.shop.ShopParser.GUI.BLACKSMпїЅTH
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at com.convallyria.taleofkingdoms.common.shop.ShopParser$GUI.valueOf(ShopParser.java:25)
	at com.convallyria.taleofkingdoms.common.shop.ShopParser.addToShopItems(ShopParser.java:121)
	at com.convallyria.taleofkingdoms.common.shop.ShopParser.createShopItems(ShopParser.java:55)
	at com.convallyria.taleofkingdoms.TaleOfKingdoms.onInitialize(TaleOfKingdoms.java:162)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more

### Steps to reproduce

can you help for crash

### Expected behaviour

fixing the crash

### Mod list

just fabric.api.0.46.1+1.17

**Comment by SamB440** [comment]
1.17 isn't really supported right now, and this was fixed in a future version. However, I will leave this open for now for when we revisit these versions in the future.
