### ISSUE TITLE
Game crushed when load this mod, possibly caused by exception: java.lang.NoSuchFieldError: serverPacketHandlers

### ISSUE THREAD

**Issue by StevenDean21st** [SamB440/Tale-of-Kingdoms#154]
### Summary

Game crashed when load this mod, possibly caused by exception: `java.lang.NoSuchFieldError: serverPacketHandlers`

### Crash Report
```
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'taleofkingdoms'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: serverPacketHandlers
	at com.convallyria.taleofkingdoms.TaleOfKingdomsAPI.<init>(TaleOfKingdomsAPI.java:34)
	at com.convallyria.taleofkingdoms.TaleOfKingdoms.onInitialize(TaleOfKingdoms.java:126)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
```

### Steps to reproduce

The game crashed whilst initializing game.

### Expected behaviour

hmmm

### Mod list

+ taleofkingdoms-1.0.5
+ owo-lib-0.11.2
+ fabric-api-0.91.0

**Comment by SamB440** [comment]
Use fabric loader 0.14 or update to the latest github commit by downloading off ci or compiling it.

**Comment by Poopooracoocoo** [comment]
See #151
